### All producers
GET http://localhost:8080/api/producer
Accept: application/json

### One expl. producer containing 'ernat'
GET http://localhost:8080/api/producer?nameParam=o S
Accept: application/json

### One expl. producer containing 'bm'
GET http://localhost:8080/api/producer?nameParam=NEW_SHORTNSME4
Accept: application/json

### One expl. producer containing 'xx' -> give all
GET http://localhost:8080/api/producer?nameParam=xx
Accept: application/json

###One expl. producer containing '' -> give all
GET http://localhost:8080/api/producer?nameParam=
Accept: application/json

###One expl. producer with given id
GET http://localhost:8080/api/producer/api/producer/id?idVal=0
Accept: application/json

### Post new producer in json format
POST http://localhost:8080/api/producer
Content-Type: application/json

{
  "shortname": "NEW_SHORTNSME4",
    "name": "NEW_NAME4"
}

### Delete producer with given shortname
DELETE http://localhost:8080/api/producer/IBM
Accept: application/json

### Delete new producer with id
DELETE http://localhost:8080/api/producer/3
