
### All StorageObjectMetas
GET http://localhost:8080/api/storageObjectMeta
Accept: application/json

### One StorageObjectMeta
GET http://localhost:8080/api/storageObjectMeta?nameParam=XX
Accept: application/json
