@startuml
'https://plantuml.com/sequence-diagram

entity User {
    -email : String
    -password : String
    -role : Role
    -createdAt: LocalDateTime
    -lastLogin: LocalDateTime
    -activated: boolean
}

@enduml